version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    network_mode: bridge
    container_name: uptime-kuma
    volumes:
      - /share/ZFS24_DATA/Container/uptimekuma-config:/app/data
    ports:
      - "3001:3001"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
volumes:
  uptime-kuma: